FROM node:14
RUN apt-get update && apt-get install -y git
WORKDIR /usr/src/
RUN git clone https://github.com/application-research/estuary-www
WORKDIR /usr/src/estuary-www
RUN npm install
COPY constants.ts /usr/src/estuary-www/common/constants.ts
RUN npm run build
CMD npm run start




